# Information for actuator /info endpoint. Maven build will provide actual values.
info:
    app:
        name: @project.name@
        artifactId: @project.artifactId@
        version: @project.version@
        applicationName: ${spring.application.name}
        serverPort: ${server.port}
        
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/product
        username: root
        password: dilwit
        driver-class-name: com.mysql.jdbc.Driver
        hikari:
            max-wait: 10000
            max-active: 50
            test-on-borrow: true
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                ddl-auto: create